
new TypeIt("#subdomain", { 
    lifeLike: false, 
    speed: 0,
    loop: true
})
    .type("y")
    .pause(100)
    .type("o")
    .pause(100)
    .type("u")
    .pause(100)
    .type(".")
	.pause(100)
//	.type("f")
//	.pause(100)
//	.type(".")
//	.pause(100)
	.type("f")
	.pause(100)
	.type("r")
	.pause(100)
	.type("d")
	.pause(100)
	.type("o")
	.pause(100)
	.type("m")
	.pause(100)
	.type("a")
	.pause(100)
	.type("i")
	.pause(100)
	.type("n")
	.pause(100)
	.type("s")
	.pause(100)
	.type(".")
	.pause(100)
	.type("s")
	.pause(100)
	.type("i")
	.pause(100)
	.type("t")
	.pause(100)
	.type("e")
	.pause(5000)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(30)
	// .delete(1)
	// .pause(500)
	// .type("d")
	// .pause(100)
	// .type("m")
	// .pause(100)
	// .type("e")
	// .pause(100)
	// .type("n")
	// .pause(100)
	// .type("a")
	// .pause(100)
	// .type(".")
	// .pause(100)
	// .type("x")
	// .pause(100)
	// .type("y")
	// .pause(100)
	// .type("z")
    // .pause(5000)
    .move(-18, { delay: 100 })
    .type("y")
    .pause(100)
    .type("o")
    .pause(100)
    .type("u")
    .pause(100)
    .type("@")
    .pause(100)
    .move(+18, { delay: 100 })
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
	// .delete(1)
    // .pause(10)
    // .delete(1)
	.go();